export enum AdminActionType {
  // Recipe actions
  ADD_RECIPE = "ADD_RECIPE",
  DELETE_RECIPE = "DELETE_RECIPE",
  UPDATE_RECIPE = "UPDATE_RECIPE",
  GET_RECIPE_LIST = "GET_RECIPE_LIST",

  // Pending recipes fetch actions
  FETCH_PENDING_RECIPES_REQUEST = "FETCH_PENDING_RECIPES_REQUEST",
  FETCH_PENDING_RECIPES_SUCCESS = "FETCH_PENDING_RECIPES_SUCCESS",
  FETCH_PENDING_RECIPES_FAILURE = "FETCH_PENDING_RECIPES_FAILURE",

  // Approve recipe actions
  APPROVE_RECIPE_REQUEST = "APPROVE_RECIPE_REQUEST",
  APPROVE_RECIPE_SUCCESS = "APPROVE_RECIPE_SUCCESS",
  APPROVE_RECIPE_FAILURE = "APPROVE_RECIPE_FAILURE",

  // Reject recipe actions
  REJECT_RECIPE_REQUEST = "REJECT_RECIPE_REQUEST",
  REJECT_RECIPE_SUCCESS = "REJECT_RECIPE_SUCCESS",
  REJECT_RECIPE_FAILURE = "REJECT_RECIPE_FAILURE",

  // Add recipe actions
  ADD_RECIPE_REQUEST = "ADD_RECIPE_REQUEST",
  ADD_RECIPE_SUCCESS = "ADD_RECIPE_SUCCESS",
  ADD_RECIPE_FAILURE = "ADD_RECIPE_FAILURE",

  // Fetch all recipes actions
  FETCH_ALL_RECIPES_REQUEST = "FETCH_ALL_RECIPES_REQUEST",
  FETCH_ALL_RECIPES_SUCCESS = "FETCH_ALL_RECIPES_SUCCESS",
  FETCH_ALL_RECIPES_FAILURE = "FETCH_ALL_RECIPES_FAILURE",

  // Update recipe actions
  UPDATE_RECIPE_REQUEST = "UPDATE_RECIPE_REQUEST",
  UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS",
  UPDATE_RECIPE_FAILURE = "UPDATE_RECIPE_FAILURE",

  // Delete recipe actions
  DELETE_RECIPE_REQUEST = "DELETE_RECIPE_REQUEST",
  DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS",
  DELETE_RECIPE_FAILURE = "DELETE_RECIPE_FAILURE"
}
